H/W 2.18. Разметка главной страницы
htmlacademy-htmlcss/1629397-nerds-30 pull request #2
Opened 2021-01-27 13:48 UTC by train-octarine

Плюс blank.html

2021-01-27 19:57 UTC, dean992008 requested changes

2021-01-27 19:57 UTC, dean992008 commented on blank.html
> +<!DOCTYPE html>
Я думаю не нужно делать отдельныю страницу для сылок которых нет. На такие сылки долстаточно поставить `#`

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +      <nav>
В nav нужно обернуть только список с меню. nav долен указывать именно на главное меню.

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +          <li><a href="blank.html">СТУДИЯ</a></li>
Текст к пунктам меню нужно писать строчными буквами, мы потом в CSS сделаем их uppercase c помощью `text-transform`

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +            <h3>Долго, дорого,<br> скурпулезно.</h3>
`br` здесь не нужно.

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +              <img src="https://via.placeholder.com/760x431" alt="Картинка первого слайда">
Я бы не рекомендовал спешить с картинками. Их лучше добавлять после лекции о картинках
В конкретно этом случае это лекоративное изобрадение, а соотвесвено ее нужно будет добавлять через css как фон.

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +            <figure>
Также figure нужно использовать того для картинок с подписью. Здесь не тот случай.

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +            <h3>ВЕБ-САЙТЫ</h3>
Тоже нужно использовать строчные буквы как везде в документе.

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +            146%<br>
Здесь br тоже не нужен. А вот `146%` и ` Уровень самоотдачи` нужно обернуть в отдельные теги, во время оформления их будет удобно сделаль блочными. 

P.S. Вообще br не рекомендуется использовать без крайней необходимости, так как с ним почти всегда проблемы если делать сайт адаптивным.

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +            <figure>
Также на странице почти везде где используешь figure, он не оправдан. 
https://developer.mozilla.org/ru/docs/Web/HTML/Element/figure#%D0%BF%D1%80%D0%B8%D0%BC%D0%B5%D1%87%D0%B0%D0%BD%D0%B8%D1%8F_%D0%BF%D0%BE_%D0%B8%D1%81%D0%BF%D0%BE%D0%BB%D1%8C%D0%B7%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8E

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +        <p>
p здесь лишнее. А вот поля лучше обернуть в список.

2021-01-27 19:57 UTC, dean992008 commented on index.html
> +      <button type="button">Закрыть</button>
Эту кнопку я бы перенес в форму и сделал `type="reset"` чтобы она очищала форму при закрытии.

2021-01-27 20:59 UTC, train-octarine commented on index.html
> +            146%<br>
Привет!

Подскажи, пожалуйста, как без br делать перенос строки внутри абзаца, чтобы страничка была похожа на макет? Или убрать только в двух местах, которые указал?

2021-01-30 20:41 UTC, dean992008 commented on blank.html
> +<!DOCTYPE html>
Не исправлено. blank.html нужно удалить.

2021-01-30 20:43 UTC, dean992008 commented on index.html
> +            146%<br>
` А вот 146% и Уровень самоотдачи нужно обернуть в отдельные теги`. Потом в css им задать display: block

2021-01-30 21:00 UTC, dean992008 requested changes

2021-01-30 21:00 UTC, dean992008 commented on catalog.html
> +            <div><meter value="900" max="1500" title="Регулятор стоимости"></meter></div><!--Скорее всего, здесь будет javascript-->
Это нужно будет разметить `div`, внешние библиотеки мы не используем, а нативный работает только с одним бугенком. Поэтому нужно будет сделать похожим внешне, а одивлять не обезательно.

2021-01-30 21:00 UTC, dean992008 commented on catalog.html
> +          <li>по цене</li>
Это нужно разметить как сылки.

2021-01-30 21:00 UTC, dean992008 commented on catalog.html
> +        <button>По убыванию</button>
Это тоже сылки, и их нужно перенести в список выше.

2021-01-30 21:00 UTC, dean992008 commented on catalog.html
> +      <article>
Карта и подпись должны быть в 1 секции.

2021-01-31 21:21 UTC, dean992008 commented on catalog.html
> +          <li>по цене</li>
На сылки нужно добавить `href` и заглушки.

2021-01-31 21:22 UTC, merged